// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import DarkmodeController from './darkmode_controller'
Stimulus.register('darkmode', DarkmodeController)

import DropdownController from './dropdown_controller'
Stimulus.register('dropdown', DropdownController)

import ModalController from './modal_controller'
Stimulus.register('modal', ModalController)